### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by blase147** [kaizipaul/recipe-app#11]
## In this Project, We implemented the following:
- Set up the Kanban board and created tasks for everyone
- Link to the project: https://github.com/users/kaizipaul/projects/2/views/1
## We are a team of two:
- Team member 1 is @kaizipaul 
- Team member 2 is @blase147

**Comment by danmainah** [comment]
Hi @kaizipaul and @blase147 , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✔️  Good Description
✔️  Good design

# Required Changes ♻️

- [ ]@team  kindly add the description to the task shown in the screenshot below, this will ensure the task objective is met as the task implementor will have a guideline of what is supposed to be done.
![image](https://user-images.githubusercontent.com/61408860/221583705-1da7b720-b223-4d48-a26b-9e38431a48b5.png)

- [ ] @kaizipaul and @blase147 kindly add a task to make sure there are no N+1 queries happening, this is part of the requirement
![image](https://user-images.githubusercontent.com/61408860/221585130-6dcde6b2-76ac-4496-b141-d8f2c76d3987.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @kaizipaul, and @blase147👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
You didn't implement any of the requested changes by the previous reviewer. Please make sure to implement the below-requested changes.
- [ ] Please make sure to add a description to this task as requested in the project requirements that all tasks should have a description.
  - ![image](https://user-images.githubusercontent.com/83803414/221588122-44bde606-afb6-4aac-8ddb-ab113864d442.png)

- [ ] Please add a task to make sure there are no N+1 queries happening as requested in the project requirements.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
